-- DROP TABLE IF EXISTS BANK;
-- DROP TABLE IF EXISTS CLIENT;
-- DROP TABLE IF EXISTS CONTRACT;
-- DROP TABLE IF EXISTS ACCOUNT;
-- DROP TABLE IF EXISTS CARD;
-- DROP TABLE IF EXISTS CREDIT;
-- DROP TABLE IF EXISTS PAYMENT;
-- DROP TABLE IF EXISTS DEPOSIT;

CREATE TABLE IF NOT EXISTS BANK (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CLIENT (
    id INT NOT NULL AUTO_INCREMENT,
    uid VARCHAR(100) NOT NULL,
    UNIQUE (uid),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CONTRACT (
    id INT NOT NULL AUTO_INCREMENT,
    bank_id INT NOT NULL,
    client_id INT NOT NULL,
    creation_date DATETIME NOT NULL,
    PRIMARY KEY (id, bank_id, client_id),
    FOREIGN KEY (bank_id) REFERENCES BANK(id),
    FOREIGN KEY (client_id) REFERENCES CLIENT(id)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    bank_id INT NOT NULL,
    client_id INT NOT NULL,
    account_number VARCHAR(24) NOT NULL,
    account_value FLOAT NOT NULL,
    account_type ENUM('DEPOSIT', 'CURRENT') NOT NULL DEFAULT 'CURRENT',
    UNIQUE (client_id, bank_id, account_type),
    FOREIGN KEY (bank_id) REFERENCES BANK(id),
    FOREIGN KEY (client_id) REFERENCES CLIENT(id)
);

CREATE TABLE IF NOT EXISTS CARD (
    id INT PRIMARY KEY AUTO_INCREMENT,
    account_id INT NOT NULL,
    card_number VARCHAR(16) NOT NULL,
    cvv VARCHAR(3) NOT NULL,
    FOREIGN KEY (account_id) REFERENCES ACCOUNT(id)
);

CREATE TABLE IF NOT EXISTS CREDIT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    client_id INT,
    bank_id INT NOT NULL,
    amount_paid FLOAT,
    amount_total FLOAT NOT NULL,
    credit_state ENUM('NEW', 'UNPAID', 'PAID') NOT NULL DEFAULT 'NEW',
    FOREIGN KEY (bank_id) REFERENCES BANK(id),
    FOREIGN KEY (client_id) REFERENCES CLIENT(id)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    paid_value FLOAT NOT NULL,
    account_number VARCHAR(24) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPOSIT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    deposit_value FLOAT NOT NULL,
    account_number VARCHAR(24) NOT NULL
);